spring:
  thymeleaf:
    # ????
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/seckill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: happy
    hikari:
      # ????
      pool-name: DateHikariCP
      # ???????
      minimum-idle: 5
      # ?????????????600000?10min?
      idle-timeout: 180000
      # ?????
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ?????????0?????????1800000?30min?
      max-lifetime: 1800000
      # ?????????30000?30??
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1
  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数：默认8
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5
  #RabbitMQ
  rabbitmq:
    #服务器地址
    host: 192.168.10.101
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间 默认1000ms
        initial-interval: 1000
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000
        #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0

mybatis-plus:
  # ??Mapper.xml????
  mapper-location: classpath*:/mapper/*Mapper.xml
  # ??Mybatis????????????????
  type-aliases-package: com.example.seckill.pojo

# MyBatis SQL??????????????Mapper.xml?????
logging:
  level:
    com.example.seckill.mapper: debug